#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Aug 13 13:33:03 2025

add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/image_pcie_capture.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/ddr3/ddr3.idf"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/aq_axi_master_256_burst.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/axi_ctrl_256_burst.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/cmos_write_req_gen.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/frame_read_write_256_burst.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/mem_read_arbi.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/mem_write_arbi.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/frame_fifo_read_256_burst.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/frame_ddr3/frame_fifo_write_256_burst.v"
add_design D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/afifo_16i_128o_512/afifo_16i_128o_512.idf
add_design D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/afifo_128i_128o_512/afifo_128i_128o_512.idf
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
add_constraint "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/project.fdc"
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/pcie_test.idf"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/ips2l_pcie_dma.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_expd_apb_mux.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_controller.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_expd_apb_mux.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ips2l_pcie_dma_ram_init_param.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ips2l_pcie_dma_ram_Reset_Value.v"
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/ips2l_pcie_dma.v"
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_controller.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/pcie_test/example_design/rtl/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_expd_apb_mux.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_controller.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ips2l_pcie_dma_ram_init_param.v"
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
add_design D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/project/ipcore/clk_1080p_gen/clk_1080p_gen.idf
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/HDMI/lcd_driver.v"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/01_img_pcie_capture/source/HDMI/lcd_para.v"
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/axi_ctrl/axi4_ctrl.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/pcie/pcie_dma_ctrl/ips2l_expd_apb_mux.v"
remove_design D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/pcie_test/pcie_test.idf
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/pcie_test/pcie_test.idf"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/aq_axi_master_256_burst.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/axi_ctrl_256_burst.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/cmos_write_req_gen.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/mem_read_arbi.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/frame_read_write_256_burst.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/frame_fifo_read_256_burst.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/mem_write_arbi.v"
remove_design -verilog "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/source/frame_ddr3/frame_fifo_write_256_burst.v"
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/R_FIFO_128i_128o/R_FIFO_128i_128o.idf"
add_design "D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/W_FIFO_16i_128o/W_FIFO_16i_128o.idf"
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
remove_design -force D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/W_FIFO_16i_128o/W_FIFO_16i_128o.idf
remove_design -force D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/R_FIFO_128i_128o/R_FIFO_128i_128o.idf
add_design D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/W_FIFO_16i_128o/W_FIFO_16i_128o.idf
add_design D:/Desktop/work_material/RK_learning/RK3568_MES2L50H/05-work_material/03_FPGA_Project/02_img_pcie_capture/project/ipcore/R_FIFO_128i_128o/R_FIFO_128i_128o.idf
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
add_design D:/Desktop/video_class/camera_demo/FPGA_project/03_camera_pcie_capture_fmc/project/ipcore/pll/pll.idf
add_design "D:/Desktop/video_class/camera_demo/FPGA_project/03_camera_pcie_capture_fmc/source/cmos_8_16bit.v"
add_design "D:/Desktop/video_class/camera_demo/FPGA_project/03_camera_pcie_capture_fmc/source/i2c_com.v"
add_design "D:/Desktop/video_class/camera_demo/FPGA_project/03_camera_pcie_capture_fmc/source/ov5640_top.v"
add_design "D:/Desktop/video_class/camera_demo/FPGA_project/03_camera_pcie_capture_fmc/source/power_on_delay.v"
add_design "D:/Desktop/video_class/camera_demo/FPGA_project/03_camera_pcie_capture_fmc/source/reg_config.v"
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L50H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
add_design "D:/Desktop/work_material/video_class/camera_demo/FPGA_project/08_HDMI_pcie_capture_40pin_100k/source/HDMI/iic_dri.v"
add_design "D:/Desktop/work_material/video_class/camera_demo/FPGA_project/08_HDMI_pcie_capture_40pin_100k/source/HDMI/ms72xx_ctl.v"
add_design "D:/Desktop/work_material/video_class/camera_demo/FPGA_project/08_HDMI_pcie_capture_40pin_100k/source/HDMI/ms7200_ctl.v"
add_design "D:/Desktop/work_material/video_class/camera_demo/FPGA_project/08_HDMI_pcie_capture_40pin_100k/source/HDMI/ms7210_ctl.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
add_fic "D:/Desktop/work_material/FPGA_help_others/FPGA_RK_board/08_HDMI_pcie_capture_40pin_100k/project/synthesize/image_pcie_capture_syn.fic"
dev_map 
pnr 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -compress_bitstream true -master_configuration_clock_frequency {40M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/axi4_ctrl_tb.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/axi4_mem_model.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/dma_read_bfm.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/rgb565_frame_gen.v"
enable_pr_flow -syn_tool ads
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/source/axi_ctrl/axi4_ctrl.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
remove_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/axi4_mem_model.v"
remove_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/source/axi_ctrl/axi4_ctrl.v"
remove_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/axi4_ctrl_tb.v"
remove_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/dma_read_bfm.v"
remove_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/rgb565_frame_gen.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/axi4_mem_model.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/ddr_write_path_tb.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/rgb888_frame_gen.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/models/R_FIFO_128i_128o.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/models/W_FIFO_16i_128o.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/source/hdmi_ddr_write_path.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/axi4_ctrl_tb.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/dma_read_bfm.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/rgb565_frame_gen.v"
add_design "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/dma_read_bfm.v"
add_design "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/dma_write_data_src.v"
add_design "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/host_mem_scoreboard.v"
add_design "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/ips2l_pcie_dma_tb.v"
add_design "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/sim/tb/pcie_axis_host_bfm.v"
add_simulation "C:/Users/23694/Desktop/ziguang_project/02_pcie_image_test_1080p_v1/08_HDMI_pcie_capture_40pin_100k/source/axi_ctrl/axi4_ctrl.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module image_pcie_capture
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
